#cloud-config
# Edited name
# Edited my public ssh key
# added ngnix and ufw
# added ufw commands
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEoQTI+du9kw2Ddww65IWAkqZicjjGHgLChFT59GZA0v brandnbarnet@gmail.com

packages:
  - ripgrep
  - rsync
  - nginx
  - ufw
  
runcmd:
  - sed -i 's/^#\(Storage=auto\)/\1/' /etc/systemd/journald.conf
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - systemctl restart systemd-journald
  - ufw allow SSH
  - ufw allow http
  - ufw enable
